FigureTechnologies/ats-smart-contract

.github/workflows/rust.yaml, .gitignore, Makefile, README.md
=> add codecov badge, release badge

.github/workflows/rust.yaml, .tarpaulin.toml
=> add tarpaulin xml report generation github action for codecov.io upload

src/contract.rs
=> refactor order data in response attributes

.github/workflows/rust.yaml, src/contract.rs
=> change order price comparison to use the decimal types, not strings

src/contract.rs
missed the execute match response attributes
closes #26
=> add order data to execute match response attributes

schema/contract_info.json, schema/instantiate_msg.json, src/contract.rs, src/contract_info.rs, src/error.rs, src/msg.rs
=> add price_precision and size_increment restrictions on orders

src/contract.rs
=> allow both orders in a match to partially fill

Cargo.lock, Cargo.toml, src/contract.rs, src/msg.rs
=> validate order id as UUID

.github/workflows/rust.yaml, Makefile, src/contract.rs
=> return 'id' field error when creating orders if order with that id exists

src/contract.rs, src/lib.rs, src/msg.rs
=> add migrate function

.github/workflows/rust.yaml
see https://github.com/codecov/codecov-action/issues/330
=> temporarily disable codecov fail on error.

Cargo.lock, Cargo.toml, README.md, src/contract.rs, src/error.rs
=> change approve/create ask response class attribute to json serialization

Cargo.lock, Cargo.toml, src/contract.rs, src/contract_info.rs
=> fix fee_rate and fee_account not saving when initializing

Cargo.lock, Cargo.toml, schema/ask_order_v1.json, schema/bid_order_v1.json, schema/contract_info_v2.json, schema/execute_msg.json, src/contract.rs, src/msg.rs
closes #67 
Piggybacking off of the expiration code
=> handle reject ask and bid order

Cargo.lock, Cargo.toml, Makefile, README.md, src/ask_order.rs, src/bid_order.rs, src/contract.rs, src/contract_info.rs, src/version_info.rs
closes #86 
This makes the required updates for the smart contract to work with provenance 1.8
- Updates CosmWasm  and provwasm dependencies to 1.0.0-beta
- Updates the rust optimizer version to 0.12.5
=> Issue/86 - Provenance 1.8 upgrade

src/bid_order.rs
Reduces gas costs for migration of recent contracts by only running the bid order migration if the contract version is < 16.3
=> optimize bid orders migration

Cargo.lock, Cargo.toml, src/contract.rs, src/error.rs, src/msg.rs, src/tests/execute/cancel_ask_tests.rs, src/tests/execute/execute_match_tests.rs, src/tests/execute/expire_ask_tests.rs, src/util.rs, src/version_info.rs
Part 1
wasm size before:
- 530296
wasm size after:
- 527517
=> Minor code improvements

src/contract.rs, src/tests/execute/execute_match_tests.rs, src/util.rs
final changes before official 0.17.4 release
=> Minor fixes

README.md
I've updated the README to match the more accurate instructions outlined in https://hackmd.io/TLVyhpL3SFSyHQKdxggduw.
I verified the output look correct and links work correct by rendering the markdown locally as well. This was the process I used to write the setup script used for the profiler (https://github.com/FigureTechnologies/ats-smart-contract/pull/108/files#diff-ce97d4db0d718ad6734276458ed055d488c80c0a31a3e86cff24778a58ef191b)
=> Update README to match currently working instructions

Cargo.lock, Cargo.toml, README.md
Bump version of the contract from `v0.19.2` to `v0.19.3`
=> Bump contract version

Cargo.lock, Cargo.toml, README.md, src/execute/modify_contract.rs, src/tests/execute/execute_modify_tests.rs
- Made a function to check some contract modifications
- fee rate is a function, with same logic for ask and bid
- pulled the attribute check into a function as well
=> Check fee rate on ask/bid fee change

src/contract.rs, src/util.rs
addressing https://github.com/FigureTechnologies/ats-smart-contract/pull/118#discussion_r1326569650
=> sc-238700: create add transfer function for repetitive action
